import Head from 'next/head'
import Link from 'next/link'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Profile from './profile'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className={styles.heading}>hello world</h1>
      <ul>
                <li>
                    getStaticProps : 
                    <Link href={'/profile'}>Profile Page</Link>
                </li>
                <li>
                    getStaticPaths : 
                    <Link href={'/1'}>User 1</Link>
                </li>
                <li>
                    getServerSideProps : 
                    <Link href={'/Posts'}>Posts Page</Link>
                </li>
            </ul>
      </main>
    </>
  )
}
